import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@radix-ui/themes/styles.css";
import './theme-config.css';
import "./globals.css";

import { Container, Theme } from '@radix-ui/themes'

import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={inter.variable} >
        <AuthProvider>
        <Theme accentColor="violet" grayColor="sage" radius="large" scaling="110%">
        
        <NavBar />

          <main>
            <Container>
              {children}
              </Container>       
          </main>
      </Theme>
        </AuthProvider>
      
        
      </body>
    </html>
  );
}
