import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";

import "@radix-ui/themes/styles.css";
import './theme-config.css';
import "./globals.css";

import { Theme, ThemePanel } from '@radix-ui/themes'

import NavBar from "./NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={inter.variable} >
      <Theme accentColor="violet" grayColor="sage" radius="large" scaling="110%">
        
          <NavBar />
            <main className="p-5">

              {children}
            </main>
            
        </Theme>
        
      </body>
    </html>
  );
}
